; Asm codes generated by Shanghai Haier C Compiler
; HRCO, Ver: 1.0,0133

#INCLUDE       	<ES7P0693.INC>
#INCLUDE       	<OPERATION.INC>
	EXTERN         	MUL_TEMP
	EXTERN         	MUL_TEMP
	EXTERN         	_Uart_Init
	EXTERN         	_ADC_init
	EXTERN         	_ADC_dis_init
	EXTERN         	_UART_send
	EXTERN         	_UART_sendDATA
	EXTERN         	_User_Get_measure_Val_10ms
	EXTERN         	_Send_test
	EXTERN         	_User_Get_measure_Val
	EXTERN         	_vcc_val
	EXTERN         	_RV
	EXTERN         	_RT
	EXTERN         	_Tmp
	EXTERN         	_Task_1
	EXTERN         	_Task_5
	EXTERN         	_Task_10
	EXTERN         	_Task_50
	EXTERN         	_Task_100
	EXTERN         	_Task_200
	EXTERN         	_Task_500
	EXTERN         	_Task_1000
	EXTERN         	_SetTime
	EXTERN         	_GetTime
	EXTERN         	_GetTimeDATA
	EXTERN         	_CompareTime
	EXTERN         	_CompareTimeDATA
	EXTERN         	_key_status
	EXTERN         	_key_busy
	PUBLIC         	_touch_key_busy
	PUBLIC         	_touch_key_staus
	PUBLIC         	_scan_touch_key
	EXTERN         	_scan_key
	EXTERN         	_Set_LED
	EXTERN         	_Set_LEDDATA
	EXTERN         	_LED_Clear
	EXTERN         	_Updata_SCAN_LED_BUF_L
	EXTERN         	_D1_NUM
	EXTERN         	_D1_NUMDATA
	EXTERN         	_D2_NUM
	EXTERN         	_D2_NUMDATA
	EXTERN         	_SCAN_NEW
	EXTERN         	_acos
	EXTERN         	_acosDATA
	EXTERN         	_asin
	EXTERN         	_asinDATA
	EXTERN         	_atan2
	EXTERN         	_atan2DATA
	EXTERN         	_atan
	EXTERN         	_atanDATA
	EXTERN         	_ceil
	EXTERN         	_ceilDATA
	EXTERN         	_cos
	EXTERN         	_cosDATA
	EXTERN         	_cosh
	EXTERN         	_coshDATA
	EXTERN         	_eval_poly
	EXTERN         	_eval_polyDATA
	EXTERN         	_exp
	EXTERN         	_expDATA
	EXTERN         	_fabs
	EXTERN         	_fabsDATA
	EXTERN         	_floor
	EXTERN         	_floorDATA
	EXTERN         	_frexp
	EXTERN         	_frexpDATA
	EXTERN         	_ldexp
	EXTERN         	_ldexpDATA
	EXTERN         	_log10
	EXTERN         	_log10DATA
	EXTERN         	_log
	EXTERN         	_logDATA
	EXTERN         	_pow
	EXTERN         	_powDATA
	EXTERN         	_sin
	EXTERN         	_sinDATA
	EXTERN         	_sinh
	EXTERN         	_sinhDATA
	EXTERN         	_sqrt
	EXTERN         	_sqrtDATA
	EXTERN         	_tan
	EXTERN         	_tanDATA
	EXTERN         	_tanh
	EXTERN         	_tanhDATA
	EXTERN         	_Get_Sys_time
	EXTERN         	_display_buf
	EXTERN         	_buzzer_flag
	EXTERN         	_State_flag
	EXTERN         	_temperature
	EXTERN         	_Vbat_val
	EXTERN         	_global_count
	EXTERN         	_USB_Check
_scan_touch_key_#T20290_44	EQU            	_scan_touch_keyDATA + 0X0		; Bank 0
_scan_touch_key_#T20298_44	EQU            	_scan_touch_keyDATA + 0X0		; Bank 0
_scan_touch_key_#T20391_48	EQU            	_scan_touch_keyDATA + 0X0		; Bank 0
_scan_touch_key_#T20556_51	EQU            	_scan_touch_keyDATA + 0X0		; Bank 0
#TMP	EQU            	?_TMP+ 0X10		; Bank 0
?_TMP_RET	EQU            	?_TMP		; Bank 0
_MULA_0#sh	EQU            	(MULA - 0X6080) % 0X40 + 0xC0		; Bank 0
_MULB_0#sh	EQU            	(MULB - 0X6080) % 0X40 + 0xC0		; Bank 0
_MULL_0#sh	EQU            	(MULL - 0X6080) % 0X40 + 0xC0		; Bank 0
_MULH_0#sh	EQU            	(MULH - 0X6080) % 0X40 + 0xC0		; Bank 0
_DIVEL_0#sh	EQU            	(DIVEL - 0X6080) % 0X40 + 0xC0		; Bank 0
_DIVEM_0#sh	EQU            	(DIVEM - 0X6080) % 0X40 + 0xC0		; Bank 0
_DIVSL_0#sh	EQU            	(DIVSL - 0X6080) % 0X40 + 0xC0		; Bank 0
_DIVSH_0#sh	EQU            	(DIVSH - 0X6080) % 0X40 + 0xC0		; Bank 0
_DIVQL_0#sh	EQU            	(DIVQL - 0X6080) % 0X40 + 0xC0		; Bank 0
_DIVQM_0#sh	EQU            	(DIVQM - 0X6080) % 0X40 + 0xC0		; Bank 0
_DIVRL_0#sh	EQU            	(DIVRL - 0X6080) % 0X40 + 0xC0		; Bank 0
_DIVRH_0#sh	EQU            	(DIVRH - 0X6080) % 0X40 + 0xC0		; Bank 0
_DIVC_0#sh	EQU            	(DIVC - 0X6080) % 0X40 + 0xC0		; Bank 0
_DIVEU_0#sh	EQU            	(DIVEU - 0X6080) % 0X40 + 0xC0		; Bank 0
_DIVEH_0#sh	EQU            	(DIVEH - 0X6080) % 0X40 + 0xC0		; Bank 0
_FRAH_0#sh	EQU            	(FRAH - 0X6080) % 0X40 + 0xC0		; Bank 0
_FRAL_0#sh	EQU            	(FRAL - 0X6080) % 0X40 + 0xC0		; Bank 0
	_DESC          	scan_touch_key,0X10,0X0

SECTION1scan_touch_key	UNINTIAL       	0		; Bank 0
	ORG            	0XFB		; Bank 0
_scan_touch_keyDATA	RSEG           	0X4		; Bank 0
scan_touch_key#	CSEG           
_scan_touch_key
; #include "..\main.h"
; #include "..\inc_user\key.h"
; #define Get_KEY_IO_Status()  PA2
;  		//æŒ‰é”®äº‹ä»¶å¿™æ ‡è®°ï¼Œ	
; unsigned char touch_key_busy=0;
; unsigned char touch_key_staus=0;
;   
; #define SHORT_TIME 20
; #define LONG_TIME  400
; #define DOUBLE_RELEASE_TIME_MAX 220
; #define DOUBLE_RELEASE_TIME_MIN 20	
; //1MSè¿›ä¸€æ¬¡ä¸­æ–­ï¼Œæ£€æµ‹è§¦æ‘¸æŒ‰é”®
; void scan_touch_key(){
; 	static int release_count_double;
; 	static int release_count ;
; 	static int perss_count ;
; 	static int perss_count_long;
; 	static unsigned char edge_flag;
; 	static unsigned char edge_status;
#line 23	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 		edge_flag=edge_flag<<1;
	CLR            	BKSR
;   23:(   CVUC_SC,  edge_flag ,            ,   #T20290)

; ITemplate_CVTMS_U
	SECTION        	0x2
	MOV            	(_scan_touch_key_edge_flag_44) & 0X7F,	0x0		; Bank 2
	MOVAR          	_scan_touch_key_#T20290_44		; Bank 1
;   23:(    LSH_1S,    #T20290 ,          1 , edge_flag)

; ITemplate_LSH1_4_1
	BCC            	PSW,	0x0
	SECTION        	0x1
	RL             	(_scan_touch_key_#T20290_44) & 0X7F,	0x0		; Bank 1
	MOVAR          	_scan_touch_key_edge_flag_44		; Bank 2
#line 24	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 		edge_flag+=Get_KEY_IO_Status();
;   24:(    CVB_UC,        PA2 ,            ,   #T20298)

; ITemplate_CVB_UC
	MOVI           	0x0
	JBC            	(_PA2_0)/8,	(_PA2_0)%8
	MOVI           	0x1
	MOVA           	(_scan_touch_key_#T20298_44) & 0X7F		; Bank 1
;   24:(     ADD_1,    #T20298 ,  edge_flag , edge_flag)

; ITemplate_ADD1_4
	MOV            	(_scan_touch_key_#T20298_44) & 0X7F,	0x0		; Bank 1
	SECTION        	0x2
	ADD            	(_scan_touch_key_edge_flag_44) & 0X7F,	0x0		; Bank 2
	MOVA           	(_scan_touch_key_edge_flag_44) & 0X7F		; Bank 2
; 			
; 			//edge_flag=(edge_flag|0x03);
#line 27	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 			if(edge_flag == 0x0F){
;   27:(    JNEQ_1,         15 ,  edge_flag ,   #L20302)

; ITemplate_JNEQ1_4
	MOV            	(_scan_touch_key_edge_flag_44) & 0X7F,	0x0		; Bank 2
	XORI           	0xf
	JBS            	PSW,	0x2
	GOTO           	#L20302
#line 28	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 				edge_status=1;				//ä¸Šå‡å»¶
;   28:(    ASGN_1,          1 ,            ,edge_status)

; ITemplate_ASGN1_4_R
	MOVI           	0x1
	MOVA           	(_scan_touch_key_edge_status_44) & 0X7F		; Bank 2
#line 29	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 				release_count_double=release_count;
;   29:(    ASGN_2, release_count ,            ,release_count_double)

; ITemplate_ASGN1_4_R
	MOV            	(_scan_touch_key_release_count_44+0x1) & 0X7F,	0x0		; Bank 2
	MOVA           	(_scan_touch_key_release_count_double_44+0x1) & 0X7F		; Bank 2
	MOV            	(_scan_touch_key_release_count_44) & 0X7F,	0x0		; Bank 2
	MOVA           	(_scan_touch_key_release_count_double_44) & 0X7F		; Bank 2
#line 30	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 				release_count=0;
;   30:(    ASGN_2,          0 ,            ,release_count)

; ITemplate_CLR1_4_TMP
	CLR            	(_scan_touch_key_release_count_44) & 0X7F		; Bank 2
	CLR            	(_scan_touch_key_release_count_44+0x1) & 0X7F		; Bank 2
#line 31	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 			}
;   31:(       JMP,            ,            ,   #L20300)

; ITemplate_JMP
	GOTO           	#L20300
#line 32	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 			else if(edge_flag == 0xF0){
;   32:(     LABEL,    #L20302 ,            ,          )

; ITemplate_LABEL
#L20302
;   32:(    JNEQ_1,        240 ,  edge_flag ,   #L20300)

; ITemplate_JNEQ1_4
	MOV            	(_scan_touch_key_edge_flag_44) & 0X7F,	0x0		; Bank 2
	XORI           	0xf0
	JBS            	PSW,	0x2
	GOTO           	#L20300
#line 33	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 				if(buzzer_flag!=1 && State_flag!=3){
;   33:(     JEQ_1,          1 , buzzer_flag ,   #L20338)

; ITemplate_JEQ1_4
	SECTION        	0x1
	MOV            	(_buzzer_flag) & 0X7F,	0x0		; Bank 1
	XORI           	0x1
	JBC            	PSW,	0x2
	GOTO           	#L20338
;   33:(     JEQ_1,          3 , State_flag ,   #L20338)

; ITemplate_JEQ1_4
	MOV            	(_State_flag) & 0X7F,	0x0		; Bank 1
	XORI           	0x3
	JBC            	PSW,	0x2
	GOTO           	#L20338
#line 34	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 					buzzer_flag=1;
;   34:(    ASGN_1,          1 ,            ,buzzer_flag)

; ITemplate_ASGN1_4_R
	MOVI           	0x1
	MOVA           	(_buzzer_flag) & 0X7F		; Bank 1
#line 35	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 				}
;   35:(     LABEL,    #L20338 ,            ,          )

; ITemplate_LABEL
#L20338
#line 36	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 				edge_status=0;				//ä¸‹é™å»¶
;   36:(    ASGN_1,          0 ,            ,edge_status)

; ITemplate_CLR1_4_TMP
	SECTION        	0x2
	CLR            	(_scan_touch_key_edge_status_44) & 0X7F		; Bank 2
#line 37	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 			}
;   37:(     LABEL,    #L20300 ,            ,          )

; ITemplate_LABEL
#L20300
#line 38	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 			if(edge_status){
;   38:(      JZ_1, edge_status ,            ,   #L20366)

; ITemplate_JZ1_4
	MOV            	(_scan_touch_key_edge_status_44) & 0X7F,	0x0		; Bank 2
	JBC            	PSW,	0x2
	GOTO           	#L20366
#line 39	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 					release_count++;
;   39:(     ADD_2, release_count ,          1 ,release_count)

; ITemplate_INC_2_TMP
	INC            	(_scan_touch_key_release_count_44) & 0X7F		; Bank 2
	JBS            	PSW,	0x2
	GOTO           	#L20577
	INC            	(_scan_touch_key_release_count_44+0x1) & 0X7F		; Bank 2
#L20577
#line 40	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 					if(release_count>65530)release_count=65530;
;   40:(   CVSI_SL, release_count ,            ,   #T20391)

; ITemplate_CVTMS_S
	MOV            	(_scan_touch_key_release_count_44) & 0X7F,	0x0		; Bank 2
	MOVAR          	_scan_touch_key_#T20391_48		; Bank 1
	MOV            	(_scan_touch_key_release_count_44+0x1) & 0X7F,	0x0		; Bank 2
	MOVAR          	_scan_touch_key_#T20391_48+0x1		; Bank 1
	MOVI           	0x0
	SECTION        	0x1
	JBC            	(_scan_touch_key_#T20391_48+0x1) & 0X7F,	0x7		; Bank 1
	MOVI           	0xff
	MOVA           	(_scan_touch_key_#T20391_48+0x2) & 0X7F		; Bank 1
	MOVA           	(_scan_touch_key_#T20391_48+0x3) & 0X7F		; Bank 1
;   40:(    JLE_4S,    #T20391 ,      65530 ,   #L20364)

; ITemplate_JLE1_4S
	MOVI           	0x0
	XORI           	0x80
	MOVAR          	?_TMP		; Bank 0
	MOV            	(_scan_touch_key_#T20391_48+0x3) & 0X7F,	0x0		; Bank 1
	XORI           	0x80
	SECTION        	0x0
	SUB            	(?_TMP) & 0X7F,	0x0		; Bank 0
	JBS            	PSW,	0x2
	GOTO           	#L20578
	SECTION        	0x1
	MOV            	(_scan_touch_key_#T20391_48+0x2) & 0X7F,	0x0		; Bank 1
	SUBI           	0x0
	JBS            	PSW,	0x2
	GOTO           	#L20578
	MOV            	(_scan_touch_key_#T20391_48+0x1) & 0X7F,	0x0		; Bank 1
	SUBI           	0xff
	JBS            	PSW,	0x2
	GOTO           	#L20578
	MOV            	(_scan_touch_key_#T20391_48) & 0X7F,	0x0		; Bank 1
	SUBI           	0xfa
	JBS            	PSW,	0x2
	GOTO           	#L20578
#L20578
	JBC            	PSW,	0x0
	GOTO           	#L20364
;   40:(    ASGN_2,         -6 ,            ,release_count)

; ITemplate_ASGN1_4_R
	MOVI           	0xff
	SECTION        	0x2
	MOVA           	(_scan_touch_key_release_count_44+0x1) & 0X7F		; Bank 2
	MOVI           	0xfa
	MOVA           	(_scan_touch_key_release_count_44) & 0X7F		; Bank 2
#line 41	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 			}
;   41:(       JMP,            ,            ,   #L20364)

; ITemplate_JMP
	GOTO           	#L20364
#line 42	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 			else{
;   42:(     LABEL,    #L20366 ,            ,          )

; ITemplate_LABEL
#L20366
#line 43	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 					perss_count++;
;   43:(     ADD_2, perss_count ,          1 ,perss_count)

; ITemplate_INC_2_TMP
	INC            	(_scan_touch_key_perss_count_44) & 0X7F		; Bank 2
	JBS            	PSW,	0x2
	GOTO           	#L20579
	INC            	(_scan_touch_key_perss_count_44+0x1) & 0X7F		; Bank 2
#L20579
#line 44	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 					perss_count_long++;
;   44:(     ADD_2, perss_count_long ,          1 ,perss_count_long)

; ITemplate_INC_2_TMP
	INC            	(_scan_touch_key_perss_count_long_44) & 0X7F		; Bank 2
	JBS            	PSW,	0x2
	GOTO           	#L20580
	INC            	(_scan_touch_key_perss_count_long_44+0x1) & 0X7F		; Bank 2
#L20580
#line 45	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 			}
;   45:(     LABEL,    #L20364 ,            ,          )

; ITemplate_LABEL
#L20364
#line 46	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 			if(touch_key_busy==1){
;   46:(     JEQ_1,          1 , touch_key_busy ,   #L20576)

; ITemplate_JEQ1_4
	SECTION        	0x1
	MOV            	(_touch_key_busy) & 0X7F,	0x0		; Bank 1
	XORI           	0x1
	JBC            	PSW,	0x2
	GOTO           	#L20576
; 			}
; 			else{
; 			
; 			//æŒ‰é”®é‡Šæ”¾ å¤§äºŽåŒå‡»æœ€å¤§æ—¶é—´åŽè¿›è¡Œå¤„ç†
#line 51	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 			if(release_count==(DOUBLE_RELEASE_TIME_MAX)){
;   51:(    JNEQ_2,        220 , release_count ,   #L20442)

; ITemplate_JNEQ1_4
	SECTION        	0x2
	MOV            	(_scan_touch_key_release_count_44) & 0X7F,	0x0		; Bank 2
	XORI           	0xdc
	JBS            	PSW,	0x2
	GOTO           	#L20581
	MOV            	(_scan_touch_key_release_count_44+0x1) & 0X7F,	0x0		; Bank 2
	XORI           	0x0
	JBS            	PSW,	0x2
#L20581
	GOTO           	#L20442
#line 52	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 				if( release_count_double>DOUBLE_RELEASE_TIME_MIN  &&  release_count_double<DOUBLE_RELEASE_TIME_MAX ){
;   52:(    JLE_2S, release_count_double ,         20 ,   #L20451)

; ITemplate_JLE1_4S
	MOVI           	0x0
	XORI           	0x80
	SECTION        	0x0
	MOVA           	(?_TMP) & 0X7F		; Bank 0
	MOVRA          	_scan_touch_key_release_count_double_44+0x1		; Bank 2
	XORI           	0x80
	SUB            	(?_TMP) & 0X7F,	0x0		; Bank 0
	JBS            	PSW,	0x2
	GOTO           	#L20582
	SECTION        	0x2
	MOV            	(_scan_touch_key_release_count_double_44) & 0X7F,	0x0		; Bank 2
	SUBI           	0x14
	JBS            	PSW,	0x2
	GOTO           	#L20582
#L20582
	JBC            	PSW,	0x0
	GOTO           	#L20451
;   52:(    JGE_2S, release_count_double ,        220 ,   #L20451)

; ITemplate_JGE1_4S
	SECTION        	0x2
	MOV            	(_scan_touch_key_release_count_double_44+0x1) & 0X7F,	0x0		; Bank 2
	XORI           	0x80
	MOVAR          	?_TMP		; Bank 0
	MOVI           	0x0
	XORI           	0x80
	SECTION        	0x0
	SUB            	(?_TMP) & 0X7F,	0x0		; Bank 0
	JBS            	PSW,	0x2
	GOTO           	#L20583
	MOVI           	0xdc
	SECTION        	0x2
	SUB            	(_scan_touch_key_release_count_double_44) & 0X7F,	0x0		; Bank 2
	JBS            	PSW,	0x2
	GOTO           	#L20583
#L20583
	JBC            	PSW,	0x0
	GOTO           	#L20451
#line 53	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 					touch_key_staus=DOUBLE;
;   53:(    ASGN_1,          3 ,            ,touch_key_staus)

; ITemplate_ASGN1_4_R
	MOVI           	0x3
	SECTION        	0x1
	MOVA           	(_touch_key_staus) & 0X7F		; Bank 1
#line 54	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 					touch_key_busy=1;
;   54:(    ASGN_1,          1 ,            ,touch_key_busy)

; ITemplate_ASGN1_4_R
	MOVI           	0x1
	MOVA           	(_touch_key_busy) & 0X7F		; Bank 1
#line 55	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 				}
;   55:(       JMP,            ,            ,   #L20449)

; ITemplate_JMP
	GOTO           	#L20449
#line 56	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 			  else if(SHORT_TIME < perss_count &&  perss_count<LONG_TIME ){
;   56:(     LABEL,    #L20451 ,            ,          )

; ITemplate_LABEL
#L20451
;   56:(    JGE_2S,         20 , perss_count ,   #L20479)

; ITemplate_JGE1_4S
	MOVI           	0x0
	XORI           	0x80
	SECTION        	0x0
	MOVA           	(?_TMP) & 0X7F		; Bank 0
	MOVRA          	_scan_touch_key_perss_count_44+0x1		; Bank 2
	XORI           	0x80
	SUB            	(?_TMP) & 0X7F,	0x0		; Bank 0
	JBS            	PSW,	0x2
	GOTO           	#L20584
	SECTION        	0x2
	MOV            	(_scan_touch_key_perss_count_44) & 0X7F,	0x0		; Bank 2
	SUBI           	0x14
	JBS            	PSW,	0x2
	GOTO           	#L20584
#L20584
	JBC            	PSW,	0x0
	GOTO           	#L20479
;   56:(    JGE_2S, perss_count ,        400 ,   #L20479)

; ITemplate_JGE1_4S
	SECTION        	0x2
	MOV            	(_scan_touch_key_perss_count_44+0x1) & 0X7F,	0x0		; Bank 2
	XORI           	0x80
	MOVAR          	?_TMP		; Bank 0
	MOVI           	0x1
	XORI           	0x80
	SECTION        	0x0
	SUB            	(?_TMP) & 0X7F,	0x0		; Bank 0
	JBS            	PSW,	0x2
	GOTO           	#L20585
	MOVI           	0x90
	SECTION        	0x2
	SUB            	(_scan_touch_key_perss_count_44) & 0X7F,	0x0		; Bank 2
	JBS            	PSW,	0x2
	GOTO           	#L20585
#L20585
	JBC            	PSW,	0x0
	GOTO           	#L20479
#line 57	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 					touch_key_staus=SHORT;
;   57:(    ASGN_1,          1 ,            ,touch_key_staus)

; ITemplate_ASGN1_4_R
	MOVI           	0x1
	SECTION        	0x1
	MOVA           	(_touch_key_staus) & 0X7F		; Bank 1
#line 58	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 					touch_key_busy=1;
;   58:(    ASGN_1,          1 ,            ,touch_key_busy)

; ITemplate_ASGN1_4_R
	MOVI           	0x1
	MOVA           	(_touch_key_busy) & 0X7F		; Bank 1
#line 59	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 				}
;   59:(       JMP,            ,            ,   #L20449)

; ITemplate_JMP
	GOTO           	#L20449
#line 60	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 				else if( perss_count>LONG_TIME ){
;   60:(     LABEL,    #L20479 ,            ,          )

; ITemplate_LABEL
#L20479
;   60:(    JLE_2S, perss_count ,        400 ,   #L20449)

; ITemplate_JLE1_4S
	MOVI           	0x1
	XORI           	0x80
	SECTION        	0x0
	MOVA           	(?_TMP) & 0X7F		; Bank 0
	MOVRA          	_scan_touch_key_perss_count_44+0x1		; Bank 2
	XORI           	0x80
	SUB            	(?_TMP) & 0X7F,	0x0		; Bank 0
	JBS            	PSW,	0x2
	GOTO           	#L20586
	SECTION        	0x2
	MOV            	(_scan_touch_key_perss_count_44) & 0X7F,	0x0		; Bank 2
	SUBI           	0x90
	JBS            	PSW,	0x2
	GOTO           	#L20586
#L20586
	JBC            	PSW,	0x0
	GOTO           	#L20449
#line 61	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 					touch_key_staus=LONG;
;   61:(    ASGN_1,          2 ,            ,touch_key_staus)

; ITemplate_ASGN1_4_R
	MOVI           	0x2
	SECTION        	0x1
	MOVA           	(_touch_key_staus) & 0X7F		; Bank 1
#line 62	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 					touch_key_busy=1;
;   62:(    ASGN_1,          1 ,            ,touch_key_busy)

; ITemplate_ASGN1_4_R
	MOVI           	0x1
	MOVA           	(_touch_key_busy) & 0X7F		; Bank 1
#line 63	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 				}
;   63:(     LABEL,    #L20449 ,            ,          )

; ITemplate_LABEL
#L20449
; //				LOG_I("touch_key_staus=%d",touch_key_staus);
; //				LOG_I("perss_count=%d",perss_count);
; //				LOG_I("release_count_double=%d",release_count_double);
#line 67	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 				 release_count_double=0;
;   67:(    ASGN_2,          0 ,            ,release_count_double)

; ITemplate_CLR1_4_TMP
	SECTION        	0x2
	CLR            	(_scan_touch_key_release_count_double_44) & 0X7F		; Bank 2
	CLR            	(_scan_touch_key_release_count_double_44+0x1) & 0X7F		; Bank 2
#line 68	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 				 perss_count=0;
;   68:(    ASGN_2,          0 ,            ,perss_count)

; ITemplate_CLR1_4_TMP
	CLR            	(_scan_touch_key_perss_count_44) & 0X7F		; Bank 2
	CLR            	(_scan_touch_key_perss_count_44+0x1) & 0X7F		; Bank 2
#line 69	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 				  perss_count_long=0;
;   69:(    ASGN_2,          0 ,            ,perss_count_long)

; ITemplate_CLR1_4_TMP
	CLR            	(_scan_touch_key_perss_count_long_44) & 0X7F		; Bank 2
	CLR            	(_scan_touch_key_perss_count_long_44+0x1) & 0X7F		; Bank 2
#line 70	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 			}
;   70:(       JMP,            ,            ,   #L20576)

; ITemplate_JMP
	GOTO           	#L20576
#line 71	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 			else if(perss_count_long>LONG_TIME*1.5){
;   71:(     LABEL,    #L20442 ,            ,          )

; ITemplate_LABEL
#L20442
;   71:(    CVSI_F, perss_count_long ,            ,   #T20556)

; ITemplate_LibFunc1
	MOV            	(_scan_touch_key_perss_count_long_44) & 0X7F,	0x0		; Bank 2
	MOVAR          	?_TMP		; Bank 0
	MOV            	(_scan_touch_key_perss_count_long_44+0x1) & 0X7F,	0x0		; Bank 2
	MOVAR          	?_TMP+0x1		; Bank 0
	SEGMENTSEL     	SW2FL
	SECTION        	0x0
	CALL           	SW2FL		; Bank 0		; ShBank 0
	SEGMENTSEL     	$
	MOV            	(?_TMP) & 0X7F,	0x0		; Bank 0
	MOVAR          	_scan_touch_key_#T20556_51		; Bank 1
	MOV            	(?_TMP+0x1) & 0X7F,	0x0		; Bank 0
	MOVAR          	_scan_touch_key_#T20556_51+0x1		; Bank 1
	MOV            	(?_TMP+0x2) & 0X7F,	0x0		; Bank 0
	MOVAR          	_scan_touch_key_#T20556_51+0x2		; Bank 1
;   71:(     JLE_F,    #T20556 , 600.000000 ,   #L20576)

; ITemplate_JLE_D
	MOVRA          	_scan_touch_key_#T20556_51		; Bank 1
	MOVA           	(?_TMP+0x3) & 0X7F		; Bank 0
	MOVRA          	_scan_touch_key_#T20556_51+0x1		; Bank 1
	MOVA           	(?_TMP+0x4) & 0X7F		; Bank 0
	MOVRA          	_scan_touch_key_#T20556_51+0x2		; Bank 1
	MOVA           	(?_TMP+0x5) & 0X7F		; Bank 0
	MOVI           	0x0
	MOVA           	(?_TMP) & 0X7F		; Bank 0
	MOVI           	0x16
	MOVA           	(?_TMP+0x1) & 0X7F		; Bank 0
	MOVI           	0x44
	MOVA           	(?_TMP+0x2) & 0X7F		; Bank 0
	SEGMENTSEL     	FLCMP
	CALL           	FLCMP		; Bank 0		; ShBank 0
	SEGMENTSEL     	$
	JBC            	PSW,	0x0
	GOTO           	#L20576
#line 72	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 					touch_key_staus=LONG_NO_RELEASE;
;   72:(    ASGN_1,          4 ,            ,touch_key_staus)

; ITemplate_ASGN1_4_R
	MOVI           	0x4
	SECTION        	0x1
	MOVA           	(_touch_key_staus) & 0X7F		; Bank 1
#line 73	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 					touch_key_busy=1;
;   73:(    ASGN_1,          1 ,            ,touch_key_busy)

; ITemplate_ASGN1_4_R
	MOVI           	0x1
	MOVA           	(_touch_key_busy) & 0X7F		; Bank 1
#line 74	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; 					perss_count_long=0;
;   74:(    ASGN_2,          0 ,            ,perss_count_long)

; ITemplate_CLR1_4_TMP
	SECTION        	0x2
	CLR            	(_scan_touch_key_perss_count_long_44) & 0X7F		; Bank 2
	CLR            	(_scan_touch_key_perss_count_long_44+0x1) & 0X7F		; Bank 2
; 			}
; 	}
#line 77	D:\Developmentfolder\Mixing_cup\½Á°è±­³ÌÐò\user_code_NEW\HRCC Project Application1\HRCC Project Application1\Src_user\key.c ; }
;   77:(     LABEL,    #L20576 ,            ,          )

; ITemplate_LABEL
#L20576
;   77:(       RET,            ,            ,          )

; ITemplate_RET
	SECTION        	0x0
	RET            			; Bank 0		; ShBank 0

SECTION8D__Developmentfolder_Mixing_cup_½Á°è±­³ÌÐò_user_code_NEW_HRCC_Project_Application1_HRCC_Project_Application1_Src_user_key_c_STATIC45	PSECT	FLAG=0X1088,ADDR=0X7FD42
_PA2_0	RSEG           	0X1		; Bank 0

SECTION1ID__Developmentfolder_Mixing_cup_½Á°è±­³ÌÐò_user_code_NEW_HRCC_Project_Application1_HRCC_Project_Application1_Src_user_key_c47	IDATA          		0X85		; Bank 0
_touch_key_busy	DB             	0X0,0XE4		; Bank 0

SECTION1ID__Developmentfolder_Mixing_cup_½Á°è±­³ÌÐò_user_code_NEW_HRCC_Project_Application1_HRCC_Project_Application1_Src_user_key_c49	IDATA          		0X86		; Bank 0
_touch_key_staus	DB             	0X0,0XE4		; Bank 0

SECTION2D__Developmentfolder_Mixing_cup_½Á°è±­³ÌÐò_user_code_NEW_HRCC_Project_Application1_HRCC_Project_Application1_Src_user_key_c_STATIC	UNINTIAL       	0		; Bank 0
	ORG            	0X10F		; Bank 0
_scan_touch_key_release_count_double_44	RSEG           	0X2		; Bank 0
	ORG            	0X10D		; Bank 0
_scan_touch_key_release_count_44	RSEG           	0X2		; Bank 0
	ORG            	0X109		; Bank 0
_scan_touch_key_perss_count_44	RSEG           	0X2		; Bank 0
	ORG            	0X10B		; Bank 0
_scan_touch_key_perss_count_long_44	RSEG           	0X2		; Bank 0
	ORG            	0X102		; Bank 0
_scan_touch_key_edge_flag_44	RSEG           	0X1		; Bank 0
	ORG            	0X103		; Bank 0
_scan_touch_key_edge_status_44	RSEG           	0X1		; Bank 0
	END
